aliases = {
    "Rathalos S Noir Corne": ["Noir"],
    "Amiya": ["Donkey"],
    "Jessica": ["Depressed cat", "Rich", "Sad cat"],
    "Jessica the Liberated": ["Depressed cat", "Rich", "Sad cat"],
    "Kroos": ["Kokodayo"],
    "Kroos the Keen Glint": ["Kokodayo"],
    "Młynar": ["Uncle", "Shwing"],
    "Lappland": ["Lappy"],
    "Melantha": ["Kyostinv"],
    "Kal'tsit": ["Old Well", "Well", "Ex wife", "Hag", "Fossil", "Harmacist"],
    "Ch'en": ["Waifu", "Lung Wrath", "Female Tourist C"],
    "Ch'en the Holungday": ["Waifu", "Lung Wrath", "Female Tourist C", "Balans"],
    "Lin": ["Lung Wrath", "Rat"],
    "Ling": ["Blue woman", "Bean"],
    "Nian": ["Bean"],
    "Dusk": ["Bean"],
    "Blemishine": ["Maria"],
    "W": ["Cockroach", "Wei wai wei wai", "wei wei wei wei", "Dance", "wdance","Renegade"],
    "Goldenglow": ["Dog", "Namie", "gg", "Doggo"],
    "Mizuki": ["Namie", "Armpits"],
    "SilverAsh": ["Shwing", "SA", "Bloodline"],
    "Muelsyse": ["Mumu", "Elf"],
    "Viviana": ["Candle Knight"],
    "Suzuran": ["Light", "Sob", "Our light"],
    "Harmonie": ["Smug cat"],
    "Blue Poison": ["bp", "Table"],
    "Ptilopsis": ["Table", "Tea Apple Sauce"],
    "Penance": ["Lavinia"],
    "Swire": ["Gao", "Rich"],
    "Swire the Elegant Wit": ["Gao", "Rich"],
    "Sussurro": ["Among Us"],
    "Surtr": ["Delete"],
    "Kirin R Yato": ["Delete"],
    "Texas the Omertosa": ["Delete", "Taxes"],
    "Skadi": ["Kyaa"],
    "Irene": ["4head", "5head", "Spin", "Tic Tac Toe"],
    "Siege": ["Saber"],
    "Ceobe": ["Doggo", "Kay"],
    "Saga": ["Doggo", "Doge", "Natto Gohan", "Aburaage"],
    "Chongyue": ["Kei Nario Nazasu", "Sensou Hyakushiki", "Kisamara no mondai", "KEIHA SUREBA KOUCHOU OCHIRU", "Bean"],
    "FEater": ["Po"],
    "Bagpipe": ["Coco", "Nino"],
    "Magallan": ["Pingu", "Noot noot"],
    "Passenger": ["Godsenger", "I am the storm that is approaching"],
    "Nearl the Radiant Knight": ["NTR", "Netorare"],
    "Mudrock": ["Bonk"],
    "Fiammetta": ["Angry Bird"],
    "Ho'olheyak": ["Birb", "Snek", "Shogun"],
    "Shaw": ["Rap god", "Eminem"],
    "Mostima": ["Za warudo", "Dio", "Blueberry pie"],
    "Platinum": ["Cutting board", "Ab roller"],
    "Exusiai": ["Apple pie", "Exia", "Yes Im on fire", "Ignited by a burning desire", "Drums"],
    "Eyjafjalla": ["Volcano", "Yes Im on fire", "Ignited by a burning desire", "Vocals"],
    "Eyjafjalla the Hvít Aska": ["Yes Im on fire", "Ignited by a burning desire", "Vocals"],
    "Shining": ["Yes Im on fire", "Ignited by a burning desire", "Keyboard"],
    "Gravel": ["Yes Im on fire", "Ignited by a burning desire", "Guitar"],
    "Vigna": ["Yes Im on fire", "Ignited by a burning desire", "Guitar"],
    "Hoshiguma": ["Yes Im on fire", "Ignited by a burning desire", "Bass"],
    "Asbestos": ["Yes Im on fire", "Ignited by a burning desire", "Speaker"],
    "Beanstalk": ["Breeder"],
    "Aak": ["Harmacist"],
    "Reed the Flame Shadow": ["Harmacist"],
    "Hibiscus the Purifier": ["Harmacist"],
    "Gavial the Invincible": ["Harmacist"],
    "Folinic": ["Harmacist"],
    "Saria": ["Dad"],
    "Ifrit": ["Tile"],
    "Myrtle": ["Printer"],
    "Thorns": ["Destreza"],
    "Whislash": ["Aunie"],
    "Andreana": ["Lowlight", "UmiNeko", "HaiMao"],
    "Shu": ["Bean"],
}